[application]
app ansible_host=32.197.217.96 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-practical-key.pem

[database]
db ansible_host=100.58.159.107 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-practical-key.pem
