---
- name: Install MySQL
  hosts: database
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL
      service:
        name: mysql
        state: started
        enabled: yes
